### ISSUE TITLE
Union Deriving for Parameterized Types

### ISSUE THREAD

**Issue by AnthonySuper** [morpheusgraphql/morpheus-graphql#389]
Currently, this library *very* impressively handles union types like this:

```haskell
data Character
  = CharacterDeity Deity -- Only <tyconName><conName> should generate direct link
  -- RECORDS
  | Creature { creatureName :: Text, creatureAge :: Int }
  --- Types
  | SomeDeity Deity
  | CharacterInt Int
  | SomeMutli Int Text
  --- ENUMS
  | Zeus
  | Cronus
  deriving (Generic, GQLType)
```

However, if your union type if parameterized over a monad, like this:

```haskell

data Character m = CharacterDeity (Deity m) | CharacterCreature (Creature m)

```

The inference will define types with indirection, something like:

```graphql
type CharacterDiety {
  _0: Deity!
}

type CharacterCreature {
   _0: Creature!
}

union Character = CharacterDiety | Creature
```

It would be *really* awesome if this library instead realized that these are still single-member union cases, and parameterized them like so:

```graphql
union Character = Deity | Creature
```

I dunno how hard this would be, of course!

**Comment by nalchevanidze** [comment]
hi thanks for your bug report, 

https://github.com/morpheusgraphql/morpheus-graphql/blob/04153a031dacea2908d2548d1156bc33730b611a/src/Data/Morpheus/Execution/Server/Introspect.hs#L484

https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Execution/Server/Introspect.hs#L278

i think we should check this part of code.  

this should ignore monad name from typename

https://github.com/morpheusgraphql/morpheus-graphql/blob/master/src/Data/Morpheus/Types/GQLType.hs#L112

https://github.com/morpheusgraphql/morpheus-graphql/blob/04153a031dacea2908d2548d1156bc33730b611a/src/Data/Morpheus/Types/GQLType.hs#L64


 but something does not works correctly:

**Comment by nalchevanidze** [comment]
i cant reproduce it. 

https://github.com/morpheusgraphql/morpheus-graphql/pull/390

could you please checkout actual master? i think it was fixed with some refactoring.


in this branch it works the way it should work

**Comment by AnthonySuper** [comment]
Tried it with master and it's still happening. If it helps, here's a minimal example:

https://github.com/AnthonySuper/minimal-graphql-example


The schema of this is:

```graphql
type Album {
  id: Identifier!
  name: String!
  tracks: [Song!]!
  musician: Musician!
}

type AlbumNode {
  _0: Album!
}

union AnyNode = MusicianNode | AlbumNode | SongNode

scalar Identifier

type Musician {
  id: Identifier!
  albums: [Album!]!
  songs: [Song!]!
}

type MusicianNode {
  _0: Musician!
}

type Query {
  findNode(getId: Identifier!): AnyNode!
}

type Song {
  id: Identifier!
  name: String!
  album: Album!
  musician: Musician!
}

type SongNode {
  _0: Song!
}
```

I would expect it to be more like:

```graphql
type Album {
  id: Identifier!
  name: String!
  tracks: [Song!]!
  musician: Musician!
}

union AnyNode = Musician | Album | Song

scalar Identifier

type Musician {
  id: Identifier!
  albums: [Album!]!
  songs: [Song!]!
}

type Query {
  findNode(getId: Identifier!): AnyNode!
}

type Song {
  id: Identifier!
  name: String!
  album: Album!
  musician: Musician!
}
```

**Comment by nalchevanidze** [comment]
try

```hs
data AnyNode  m=
AnyNodeMusican (Musican m)
....
```
AnyNode + Musican != MusicanNode

**Comment by AnthonySuper** [comment]
Oh, is that what the `-- Only <tyconName><conName>` comment means? In hindsight that makes sense.

I'm at work right now, but when I get home I'll change it and see if that fixes it. If it does, do you mind if I submit a quick patch slightly clarifying that documentation?

**Comment by nalchevanidze** [comment]
Yeap. Would be great if you could update documentation (to clerify, how deriving works)

**Comment by nalchevanidze** [comment]
https://github.com/morpheusgraphql/morpheus-graphql#union-types there is current documentation, i am not native english speaker, so if it is ambiguous  you are welcome to improve it

**Comment by AnthonySuper** [comment]
Since #392 got merged, I'll close this!
